development:
  bucket: mews
  access_key_id: AKIAIBXZO7RCBWHGVF3A
  secret_access_key: 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
test:
  bucket: mews
  access_key_id: AKIAIBXZO7RCBWHGVF3A
  secret_access_key: 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
production:
  bucket: mews
  access_key_id: AKIAIBXZO7RCBWHGVF3A
  secret_access_key: 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